### ISSUE TITLE
Can I hide iframe scrollbars?

### ISSUE THREAD

**Issue by baur** [ujw0l/js-overlay#1]
Hi ... thanks for the work!
It works well, but can I hide iframe scrollbars?

![image](https://user-images.githubusercontent.com/2898361/109392073-43f81180-7944-11eb-9b74-adbce28e01f8.png)

tried this, but not helps (
```
#js-modal-overlay {
  overflow: hidden;
}

#js-modal-el-container {
  overflow: hidden;
}
```

thanks!

**Comment by ujw0l** [comment]
It depends if content container is bigger than modal box it displays scroll, try increasing the size of modal box. Else try doing 
#js-modal-overlay {
  overflow: hidden !important;
}

#js-modal-el-container {
  overflow: hidden !important;
}
As I am using inline CSS so it is overwriting your style rule

**Comment by baur** [comment]
Thank you!
